apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # 主节点 mysql 的配置文件
    [mysqld]
    log-bin
    default_authentication_plugin= mysql_native_password
  slave.cnf: |
    # 从节点 mysql 的配置文件
    [mysqld]
    super-read-only
    default_authentication_plugin= mysql_native_password
