apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never
  containers:
  - name: nginx-container
    image: nginx:1.7.9
    ports:
    - containerPort: 80  # nginx 默认端口
    volumeMounts:
    - name: share-data
      mountPath: /usr/share/nginx/html
  - name: debian-container
    image: debian
    volumeMounts:
    - name: share-data
      mountPath: /pod-data
    command: ["/bin/bash"]
    args: ["-c", "echo hello from the debian container > /pod-data/index.html"]
  volumes:
  - name: share-data
    hostPath:
      path: /data
